nexus-repository-manager:
  fullnameOverride: nexus
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
    hostRepo: nexus.k8s.local

      
