nexus-repository-manager:
  fullnameOverride: nexus
  HostAliases:
    hostnames:
      - "nexus.k8s.local"
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hostRepo: nexus.k8s.local

      
