nexus-repository-manager:
  fullnameOverride: nexus
  installCRDs: false
  dex:
    enabled: false
  server:
    config:
      url: "nexus.k8s.local"
    ingress:
      enabled: true
      kubernetes.io/ingress.class: "traefik"
      ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - nexus.k8s.local
      
