---
reloader:
  reloader:
    logFormat: json
    deployment:
      resources:
        limits:
          cpu: "100m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"